name: CI/CD Pipeline

on:
    pull_request:
        branches:
            - master

jobs:
    lint-and-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18]

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm install

            - name: Run ESLint
              run: npm run lint

            - name: Run Prettier
              run: npm run prettier:check

            - name: Run Tests
              run: npm run test:run
